# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ksh.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 604)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 490, 801, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn2.setObjectName("btn2")
        self.gridLayout.addWidget(self.btn2, 0, 1, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn5.setObjectName("btn5")
        self.gridLayout.addWidget(self.btn5, 0, 4, 1, 1)
        self.btn1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 0, 0, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn3.setObjectName("btn3")
        self.gridLayout.addWidget(self.btn3, 0, 2, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn4.setObjectName("btn4")
        self.gridLayout.addWidget(self.btn4, 0, 3, 1, 1)
        self.btn6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn6.setObjectName("btn6")
        self.gridLayout.addWidget(self.btn6, 1, 0, 1, 1)
        self.btn7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn7.setObjectName("btn7")
        self.gridLayout.addWidget(self.btn7, 1, 1, 1, 1)
        self.btn8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn8.setObjectName("btn8")
        self.gridLayout.addWidget(self.btn8, 1, 2, 1, 1)
        self.btn9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn9.setObjectName("btn9")
        self.gridLayout.addWidget(self.btn9, 1, 3, 1, 1)
        self.btn10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn10.setObjectName("btn10")
        self.gridLayout.addWidget(self.btn10, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 781, 471))
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数据可视化-豆瓣影评《我和我的祖国》"))
        self.btn2.setText(_translate("MainWindow", "评级人数分布直方图"))
        self.btn5.setText(_translate("MainWindow", "点赞星数量分布饼状图"))
        self.btn1.setText(_translate("MainWindow", "关键词词云"))
        self.btn3.setText(_translate("MainWindow", "评级人数分布饼状图"))
        self.btn4.setText(_translate("MainWindow", "每个评分人数分布直方图"))
        self.btn6.setText(_translate("MainWindow", "片段好评人数分布直方图"))
        self.btn7.setText(_translate("MainWindow", "片段好评人数分布饼状图"))
        self.btn8.setText(_translate("MainWindow", "评星级人数分布饼状图"))
        self.btn9.setText(_translate("MainWindow", "评论年份分布直方图"))
        self.btn10.setText(_translate("MainWindow", "豆瓣评分人数分布直方图"))
